aiss-lifecycle-unknown-type = 0
aiss-lifecycle-testing-type = 1
aiss-lifecycle-provisioning-type = 2
aiss-lifecycle-secured-type = 3
aiss-lifecycle-non-rot-debug-type = 4
aiss-lifecycle-recoverable-rot-debug-type = 5
aiss-lifecycle-decommissioned-type = 6

aiss-lifecycle-type = 
    aiss-lifecycle-unknown-type /
    aiss-lifecycle-testing-type /
    aiss-lifecycle-provisioning-type /
    aiss-lifecycle-secured-type /
    aiss-lifecycle-non-rot-debug-type /
    aiss-lifecycle-recoverable-rot-debug-type /
    aiss-lifecycle-decommissioned-type

aiss-lifecycle = (
    aiss-lifecycle-label => aiss-lifecycle-type
)
