aiss-token = {
    aiss-nonce,
    aiss-instance-id,
    aiss-profile,
    aiss-implementation-id,
    aiss-lifecycle,
    aiss-boot-odometer,
    aiss-watermark,
}

aiss-lifecycle-label = 2500
aiss-implementation-id-label = 2501
aiss-watermark-label = 2502
aiss-boot-odometer-label = 2503

; from EAT
nonce-label = 10
ueid-label = 256
profile-label = 265
