@startuml

participant "TLS Peer" as P order 5
participant "Secure Enclave\n[TIK]" as TEP order 10
participant "Platform RoT\n[PAK]" as PRoT order 20

group Direct mode
	P -> TEP: nonce
	TEP -> PRoT: H(TIK), nonce
	PRoT -> TEP: PAT(H(TIK), nonce, EnclaveID)
	TEP -> P: PAT(H(TIK), nonce, EnclaveID),\nKAT(PoP(TIK), nonce)
end group

group Indirect mode
	group init
		TEP -> PRoT: H(TIK)
		PRoT -> TEP: PAT(H(TIK), EnclaveID)
		TEP -> TEP: cache PAT
	end group

	loop
		P -> TEP: nonce
		TEP -> P: PAT(H(TIK), EnclaveID),\nKAT(PoP(TIK), nonce)
	end
end group
